<a href="https://colab.research.google.com/github/sakshambhargava/numpy/blob/main/Unit_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Unit-1

# Introduction to Numpy

Numpy is one of the most important foundational packages for Numerical computing in python  <br><br>
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. <br>

NumPy stands for Numerical Python.

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.


# Advantages of Numpy: 

1. NumPy performs array-oriented computing.
2. It efficiently implements the multidimensional arrays.
3. It performs scientific computations.
4. It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
5. NumPy provides the in-built functions for linear algebra and random number generation

# Advantages of using Numpy Arrays Over Python Lists:

1. consumes less memory. <br>
2. fast as compared to the python List. <br>
3. convenient to use. 

# Installation of Numpy

In [ ]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


# Import Numpy and check the version? 

In [ ]:
import numpy as np
print(np.__version__)

1.19.2


# Data Types in Numpy

# NumPy Built-in Data Types

We can reference the built-in data types in NumPy by particular character code.
<br>
i – integer  
b – boolean  
u – unsigned  
f – float     
c – complex float   
m – timedelta     
M – datetime   
O – object  
S – string    
U – unicode string <br>
V – void

# Numpy Scalar Data Types

1. bool_ – It is used to return Boolean true or false values.
2. int_ – It is the default integer type (int64 or int32)
3. intc – It is identical to the integer in C (int32 or int64)
4. intp – It is the integer value used for indexing
5. int8 – It is for assigning 8-bit integer value (-128 to 127)
6. int16 – It is for assigning 16-bit integer value (-32768 to 32767)
7. int32 – It is for assigning 32-bit integer value (-2147483648 to 2147483647)
8. int32 – It is for assigning 64-bit integer value (-9223372036854775808 to 9223372036854775807)
9. uint8 – It is for assigning unsigned 8-bit integer value (0 to 255)
10. uint16 – It is for assigning unsigned 16-bit integer value (0 to 65535)
11. uint32 – It is for assigning unsigned 32-bit integer value (0 to 4294967295)
12. uint64 – It is for assigning unsigned 64-bit integer value (0 to 18446744073709551615)
13. float_ – It is to assign float values.
14. float16 – It is for half precision float values.
15. float32 – It is for single-precision float values.
16. float64 – It is for double-precision float values.
17. complex_ – It is to assign complex values.
18. complex64 – It is to represent two 32-bit float complex values (real and imaginary)
19. complex128 – It is to represent two 64-bit float complex values (real and imaginary)

### Casting
You can convert or cast an array from one data type to another

In [ ]:
arra1 = np.array([1, 2, 3, 4, 5])
print(arra1.astype(np.float64))   #Change Data Int to float.
print(arra1.dtype)

[1. 2. 3. 4. 5.]
int32


In [ ]:
# One Dimentional Arrays

import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [ ]:
# more than one dimensions 

import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [ ]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [ ]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
print(a.shape)

(3,)


In [ ]:
# Reshape Function 

import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


# How to create a boolean array?




In [ ]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# How to extract items that are Odd Numbers from 1D array?

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

# Generate Random Numbers

In [ ]:
# Random Numbers from 0 to 100 and total 10 Numbers.

print(np.random.randint(0,100, size=10,dtype=int)) 


[ 1 39 49 45 42 68 18 35 56 51]


#### Other ways to create new arrays

`ones` - to create an array of 1s<br>
`zeros` - to create array of 0s<br>
`empty` - create array without initializing its values<br>
to create higher dimensional array pass the tuple as dimension of array<br>

#### Zero
`zero()` creates an array filled with zero values. arguement is an array or tulip with size of each dimension of the array

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Ones
`ones()` - filled with one values.

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Empty
`empty()` function create an array of specified shape. Arguement is an rray or tulip with lenght of each dimension of array<br>
Value created are random and empty array needs to be assigned before use<br>

In [ ]:
np.empty((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

# `eye`, `identity` Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# Numpy ndarray - Multidimensional Array Object
`ndarray` is one of the most important feature of Numpy<br>
`ndarray` is multidimensional container of homogeneous data<br>
All the elements are of same type<br>
each `ndarray` has `shape` and data type given by `dtype` of the array

In [ ]:
import numpy as np
data = np.random.randn(2, 3)  # Random Numbers generated between 2 to 3. 
print(data)

[[ 1.34092554 -0.53189297 -1.03180517]
 [ 0.76183449  0.10177404  0.69100574]]


In [ ]:
an_arr = np.arange(1000)
print(type(an_arr))         #Type of Array. 

<class 'numpy.ndarray'>


## Combining ndarray
New ndarrary can be created.<br>
`vstack()` and `hstack` are two popular methods<br>
`vstack()` - Vertical Stack<br>
`hstack()` - Horizontal Stack<br>
<br>

### Vertical Stack
Two or more array can be stacked vertically

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])         #2D Array
print(arr1)
arr2 = np.array([[7,8,9],[10,11,12]])       #3D Array 
print(arr2)
arr3 = np.vstack((arr1, arr2))         #Combining Array in Vertical Stack. 
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### Horizontal Stack
Two or more ndarray can be stacked horizontally

In [ ]:
arr3 = np.hstack((arr1, arr2))  
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Concatenating ndarray
`concatenate()` take a sequence (tulip, list etc) and join them along input axis

In [ ]:
arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Splitting Array
divides the array into subarrays along a specified axis

Syntax:  numpy.split(ary, indices_or_sections, axis)

In [ ]:
a = np.arange(9)
print('first array')
print(a)
print('\n')
print('splitting the array in 3 equal size arrays')
b = np.split(a,3)
print(b)
print('\n')
print('splitting the array indicated first at 4, second 5- 7 remaining in 3rd')
c=np.split(a,[2,5,7])
print(c)
print('\n')

first array
[0 1 2 3 4 5 6 7 8]


splitting the array in 3 equal size arrays
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


splitting the array indicated first at 4, second 5- 7 remaining in 3rd
[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]




### Arithmetic with Numpy Array
Numpy support the batch operations on data without `for` loops. This is call as *vectorization*

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr%arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#### Comparision of array

In [ ]:
arr2 = np.array([[3,4,5],[6,7,8]])
arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2 = np.array([[1,2,6],[4,5,6]])
arr2

array([[1, 2, 6],
       [4, 5, 6]])

In [ ]:
arr2>arr1    #Show the Boolean Result

array([[False, False,  True],
       [False, False, False]])

### Array Indexing
You can access data in Numpy using Indexing

#### One Dimensional Indexing
You can access One Dimensional Indexing using bracket operator [] by specifying the zero offset value

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[0]

10

In [ ]:
10+arr[0]

20

In [ ]:
arr[-1]

50

### Two Dimensional Index
use comma to separate the index of each dimension

In [ ]:
arr2d=np.array([[10, 20, 30],[40, 50, 60]])
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
print(arr2d[0,0])
print(arr2d[1,2])
print(arr2d[1,0])

10
60
40


In [ ]:
arr2d[1,]

array([40, 50, 60])

## Array Slicing
slicing is specified using a colon operator `:` with *from* and *to* arguements<br>
`data[from:to]`

### One Dimensional Slicing
You can index all data using slice : with no index

In [ ]:
arr

array([10, 20, 30, 40, 50])

## Array Broadcasting
### Array Arithmetic Limitations
Array with different shape and size cannot be added or subtracted in Arithmetic<br>
A one dimensional array with length 8 can be added or subtracted from another array of length 8 only<br>
This limittion in arithmetic is limiting<br>
Python has buildin functionlity **broadcasting** to address this

In [ ]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


# 2D array and Scalar

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = 4
print(b)
c = a + b # scalar b will duplicate itself 5 more times to broadcast
print(c)

[[1 2 3]
 [4 5 6]]
4
[[ 5  6  7]
 [ 8  9 10]]


### 1D and 2D Array Broadcasting


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = np.array([7, 8, 9])
print(b)
c = a+b  # 1D array b is broadcast across each row of 2D by creating a copy of itself
print(c)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


# Limitations of Broadcasting

Broadcasting can be performed when<br>
1. the shape of each dimension in the array are equal<br>
or
2. one has dimension size 1

In [ ]:

import numpy as np 
  
arr = np.array([[1, 4, 3], [11, 2, 10]]) 
   
print ("Input array : ", arr)  
    
sum1 = np.cumsum(arr)    #Addition of all Elements to the Previous elements. 
print(sum1)  


Input array :  [[ 1  4  3]
 [11  2 10]]
[ 1  5  8 19 21 31]
